### ISSUE TITLE
Customize shortcut keys?

### ISSUE THREAD

**Issue by dalianzhu** [widavies/WinJump#1]
amazing tool!
Will the next version allow users to define shortcuts? 
Either UI or config files are good ways.
thanks again.

**Comment by PhilipNelson5** [comment]
I agree, on my keyboard, I have one windows key on the left side. It would be nice to be able to use <kbd>Alt</kbd> which I have access to with both hands.

**Comment by widavies** [comment]
@dalianzhu @PhilipNelson5 

Sure I can make it customizable, I also have to clean up some of the switching, occasionally it can glitch. Should be releasing a new version within a few days here.

**Comment by widavies** [comment]
I'll probably go with a configuration file, what do you guys think about something like this:

```
{
  "toggle-groups": [
    {  // create toggle groups. These allows you to group a bunch of virtual desktops.
      // When you press the toggle key it will cycle through the desktops.
	"shortcut": "win+^", 
	"desktops": [1, 2, 3]
    }
  ],
  "jump-to-1": "win+1", // custom shortcut to jump to desktop 1
  "jump-to-2": "win+2", // etc.
  "jump-to-3": "win+3",
  "jump-to-4": "win+4",
  "jump-to-5": "win+5",
  "jump-to-6": "win+6",
  "jump-to-7": "win+7",
  "jump-to-8": "win+8",
  "jump-to-9": "win+9",
  "jump-to-10": "win+0"
}
```

**Comment by PhilipNelson5** [comment]
I like the toggle-groups idea.

Another idea inspired by VSCode keybindings. It's more verbose but maybe allows for greater flexibility.

```jsonc
{
  // create toggle groups. These allows you to group a bunch of virtual desktops.
  // When you press the toggle key it will cycle through the desktops.
  "toggle-groups": [
    {
      "key": "win+^",
      "desktops": [ 1, 2, 3 ]
    }
  ],
  "keybindings": [
    {
      "key": "win+1",
      "command": "jump-to-1"
    },
    {
      "key": "ctrl+2",
      "command": "jump-to-2"
    },
    {
      "key": "alt+3",
      "command": "jump-to-3"
    }
  ]
}
```

**Comment by widavies** [comment]
Funnily enough I came to the same conclusion and then just pulled up your comment, definitely the better way to do it and makes the code a bit easier too. I'm just about finished implementing it should have a release for you soon. Thanks for the feedback.

**Comment by widavies** [comment]
@PhilipNelson5 @dalianzhu 

I just published a new release that supports configuration files. I updated the readme to explain how to write a configuration file.

Let me know if you have any issues. If it works for ya'll then I'll go ahead and close the issue.

**Comment by PhilipNelson5** [comment]
looks good to me

**Comment by widavies** [comment]
Thanks!
