### ISSUE TITLE
Can't run on windows 10

### ISSUE THREAD

**Issue by dalianzhu** [widavies/WinJump#25]
When I run the latest version, the program starts and exits, The fault module of windows will report a log. this is one of them:
```
源
WinJump

摘要
已停止工作

日期
‎2023/‎9/‎8 18:55

状态
已发送报告

问题签名
问题事件名称:	APPCRASH
应用程序名:	WinJump.exe
应用程序版本:	2.0.6.0
应用程序时间戳:	6491fd80
故障模块名称:	KERNELBASE.dll
故障模块版本:	10.0.19041.572
故障模块时间戳:	979ddb1d
异常代码:	e0434352
异常偏移:	00129ab2
OS 版本:	10.0.19042.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	2beb
其他信息 2:	2beba6fb4680d73a8c78ca7c24ccdb46
其他信息 3:	430e
其他信息 4:	430eb0c2672849df16da595cad5eb9e6

关于该问题的额外信息
存储段 ID:	ad361d0ca1d1d8fcd05763d2c4d84817 (1177519584477464599)
```

**Comment by widavies** [comment]
@dalianzhu Have you tried the 2.0.7 release? https://github.com/widavies/WinJump/releases

**Comment by widavies** [comment]
@dalianzhu Do you have a bigger error report, like [this one](https://github.com/widavies/WinJump/issues/22#issuecomment-1707435706)?

**Comment by widavies** [comment]
@dalianzhu Did you get this working? Otherwise I'm going to close out the issue.

**Comment by widavies** [comment]
@dalianzhu Did you look in Event Viewer?

**Comment by widavies** [comment]
@dalianzhu I ended up figuring this out, try the latest release https://github.com/widavies/WinJump/releases/tag/2.0.8

**Comment by dalianzhu** [comment]
I reinstalled my system, and version 2.08 ran well on the new system.

Thanks for the software, it's great
