### ISSUE TITLE
Move an application to a specific workspace

### ISSUE THREAD

**Issue by 0xNoNames** [widavies/WinJump#28]
Hello ! 
Thanks for WinJump, I will definitely use it daily in my workflow, but it would be nice if we could move any application to a specific workspace with Win+Shift+number.
I don't know how easy it is, but it's certainly possible, as other AHK scripts can do it.

**Comment by 0xNoNames** [comment]
Yes, exactly, I forgot to mention that.

**Comment by widavies** [comment]
Added in Release 2.0.8: https://github.com/widavies/WinJump/releases/tag/2.0.8
