### ISSUE TITLE
Try to find a way to not have to kill Windows explorer on startup for protected keys

### ISSUE THREAD

**Issue by widavies** [widavies/WinJump#36]

**Comment by MathisP75** [comment]
Wait, it's not supposed to kill explorer? It still does for me.

**Comment by MathisP75** [comment]
The latest version still kills explorer.exe, which is problematic for me. Is it supposed to be fixed or does it have something to do with the keys in my config? Not sure what a "protected key" is.

**Comment by widavies** [comment]
@MathisP75 It depends on what hotkeys you configure - `explorer.exe`  registers certain hotkeys itself (anything using the Windows key). If you use a hotkey like `WIN+1`, `explorer.exe` has to be restarted so we can "steal back" the global hotkey registration.

If you use a hotkey like `ALT+1`, this doesn't conflict with `explorer.exe`, so no restart is required.

Let me know if you need help configuring this.

**Comment by MathisP75** [comment]
Thank you, that's what I needed to know!

**Comment by MathisP75** [comment]
@widavies I have found quite a nice workaround for this. I want to use the Windows key, like I do on Linux, but without explorer.exe being restarted (it messes up some stuff for me). You can use PowerToys to bind the shortcuts that use the Windows key to their equivalent using the Alt key.

![Image](https://github.com/user-attachments/assets/2230e824-74dd-462a-a4aa-3d87af5c627e)
