### ISSUE TITLE
Doesn't work (v. 22631.3085)

### ISSUE THREAD

**Issue by hisbvdis** [widavies/WinJump#38]
The application doesn't run on the very last Windows version

Edition	Windows 11 Home
Version	23H2
Installed on	‎23.‎01.‎2024
OS build	22631.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by Chris24main** [comment]
I can only get V1.4 to work on this version myself..

**Comment by Chris24main** [comment]
Can confirm that V4 no longer works either. Goddammit

Edition	Windows 11 Pro
Version	23H2
Installed on	‎17/‎01/‎2024
OS build	22631.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by hisbvdis** [comment]
@widavies @PhilipNelson5

**Comment by widavies** [comment]
Working on a fix

**Comment by hisbvdis** [comment]
> Working on a fix - also I would recommend not immediately updating to Windows Preview builds. I often have to update WinJump for every Windows release and I don't have the time to continually test WinJump on preview releases.

Anyway thank you for your time and your free opensource application.
Unfortunatelly, I'm not a C-developer, that's why I have to pay freelancers to update FreeVD programm after some Windows updates.
https://github.com/hisbvdis/freevd-win-11
The only reason I prefer that program is that it allows not only move, but "copy" windows to different destops.
One of the freelancers told me that your repository helped him to update that program.

**Comment by Chris24main** [comment]
Do appreciate the effort it takes, and note the point about not installing preview updates - I should know better...

**Comment by widavies** [comment]
> Do appreciate the effort it takes, and note the point about not installing preview updates - I should know better...

@Chris24main 

Hahaha, I'm guilty of the same thing - I use ExplorerPatcher and every once I'll break it by installing a preview update.

I'll try to get updates out as fast as I can - I'm just slow sometimes.

See if this release works for you: https://github.com/widavies/WinJump/releases/tag/2.0.11
