### ISSUE TITLE
Original Filename ends .dll & Move a active window to new desktop and follow

### ISSUE THREAD

**Issue by ComputerCulture** [widavies/WinJump#39]
Hi @widavies
Hope you are well. See screenshot. original filename ends .dll
Maybe correct to .exe?

![2024-01-28_115017](https://github.com/widavies/WinJump/assets/133943765/1ff9d470-dc8d-4b7c-b8c1-00f28f2756a3)

Would it be possible at some stage to add new Keybinding to Move a active window to new desktop and follow.
Example,  alt+shift+d2 would more the active window to desktop 2 and would change to desktop 2.

Thank you Will
All the best
CC

**Comment by widavies** [comment]
@ComputerCulture It technically is a C# dll under the hood, not sure that it's a big deal. Does Original file name affect anything?

Sure thing! I added it, try this release: https://github.com/widavies/WinJump/releases/tag/2.0.13
