### ISSUE TITLE
Doesn't work in Windows 11 Pro 23H2 22631.3374

### ISSUE THREAD

**Issue by hisbvdis** [widavies/WinJump#45]

**Comment by dakka** [comment]
**Works** in my env on this version:

Edition	Windows 11 Pro
Version	23H2
Installed on	‎12/‎10/‎2023
OS build	22631.3374
Experience	Windows Feature Experience Pack 1000.22688.1000.0

**Comment by widavies** [comment]
@hisbvdis Do you have any more information? Does an error appear or does WinJump fail to start?

**Comment by mjsr-sr** [comment]
Almost fresh install here, and it works like a charm, thank you a ton devs!
