### ISSUE TITLE
Display current desktop number in the systray icon

### ISSUE THREAD

**Issue by PhilipNelson5** [widavies/WinJump#9]
It was mentioned in #6 that you were working on running WinJump in the systray. A feature to improve this would be to display the current desktop number in the WinJump systray icon. I found a couple other projects that implement this feature. Since systray icons are so small, I lean towards solutions that don't have fancy icons but instead show the current desktop number as large as possible.

- https://github.com/dankrusi/WindowsVirtualDesktopHelper
- https://github.com/esvres/vdn
- https://github.com/ridvanaltun/virtual-desktop-tray-icon
- https://github.com/m0ngr31/VirtualDesktopManager

**Comment by widavies** [comment]
I have this working, just polishing up the code a bit should be up soon.

**Comment by widavies** [comment]
Done! Take a look at the new release @PhilipNelson5

**Comment by PhilipNelson5** [comment]
This looks awesome and seems to be working so far!
